branches:
  - main

repositoryUrl: 'git@github.com:okp4/follow-contributor-action.git'

plugins:
  - - '@semantic-release/commit-analyzer'
    - releaseRules:
        - type: build
          release: patch
        - type: ci
          release: patch
        - type: docs
          release: patch
        - type: style
          release: patch
        - type: refactor
          release: patch
        - type: chore
          release: patch
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/changelog'
    - changelogFile: CHANGELOG.md
      changelogTitle: '# Follow contributor action'
  - - '@semantic-release/npm'
    - npmPublish: false
  - - "@semantic-release/github"
  - - '@semantic-release/git'
    - assets:
        - CHANGELOG.md
        - dist/
        - package.json
      message: 'chore(release): perform release ${nextRelease.version}'
