name: Lint

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

  workflow_call:

  workflow_dispatch:

jobs:
  lint-commits:
    runs-on: ubuntu-20.04
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check commits
        uses: wagoid/commitlint-github-action@v5

  lint-markdown:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Lint markdown files
        uses: avto-dev/markdown-lint@v1.5.0
        with:
          args: './*.md'
          ignore: './CHANGELOG.md'

  lint-yaml:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Lint yaml files
        uses: ibiqlik/action-yamllint@v3.1.0
        with:
          file_or_dir: ./*.yml ./.github/**/*.yml

  lint-ts:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup node environment (for building)
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.0

      - name: Fetch dependencies
        run: |
          yarn

      - name: typescript style
        run: |
          yarn format-check

      - name: Lint typescript
        run: |
          yarn lint
