name: Release

on:
  workflow_dispatch:

jobs:
  lint:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/lint.yml

  build:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build.yml

  perform-release:
    runs-on: ubuntu-20.04
    needs:
      - lint
      - build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.OKP4_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run build && npm run package

      - name: Release project
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 19.0.2
          branch: main
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/npm
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.OKP4_TOKEN }}
          GIT_AUTHOR_NAME: ${{ secrets.OKP4_BOT_GIT_AUTHOR_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.OKP4_BOT_GIT_AUTHOR_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.OKP4_BOT_GIT_COMMITTER_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.OKP4_BOT_GIT_COMMITTER_EMAIL }}
